name: trplab
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=2.305=openblas
  - blas-devel=3.11.0=5_h1ea3ea9_openblas
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.16.0=hb05425b_5
  - dbus=1.16.2=h5bd4931_0
  - eigen=3.4.0=h171cf75_1
  - expat=2.7.3=hecca717_0
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.15.0=h7e30c49_1
  - freetype=2.14.1=ha770c72_0
  - gettext=0.21.0=h39681ba_1
  - giflib=5.2.2=hd590300_0
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - harfbuzz=4.3.0=hf52aaf7_1
  - hdf5=1.12.1=h2b7332f_3
  - icu=58.2=hf484d3e_1000
  - jpeg=9e=h0b41bf4_3
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libclang=14.0.6=default_h7634d5b_1
  - libclang13=14.0.6=default_h9986a30_1
  - libcups=2.3.3=h36d4200_3
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblapacke=3.11.0=5_h6ae95b6_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopus=1.6=h0fd0de7_0
  - libpng=1.6.53=h421ea60_0
  - libpq=12.20=hdbd6064_0
  - libprotobuf=3.20.3=h3eb15da_0
  - libsqlite=3.51.1=h0c1763c_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.5.1=hffd6297_1
  - libunistring=1.3=hb25bd0a_0
  - libuuid=2.41.3=h5347b49_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=hd590300_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.10.4=hcbfbd50_0
  - libxslt=1.1.37=h873f0b0_0
  - libzlib=1.3.1=hb25bd0a_0
  - mysql=5.7.20=hf484d3e_1001
  - ncurses=6.5=h7934f7d_0
  - nettle=3.6=he412f7d_0
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - numpy=1.26.4=py39h474f0d3_0
  - openblas=0.3.30=pthreads_h6ec200e_4
  - opencv=4.6.0=py39ha16400d_5
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.0.18=hd6dcaed_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.46=hf426167_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.23=he99959a_0
  - python_abi=3.9=2_cp39
  - qt-main=5.15.2=h7358343_9
  - qt-webengine=5.15.9=h9ab4d14_7
  - qtwebkit=5.212=h3fafdc1_5
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py39h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py39h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - cloudpickle==3.1.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - filelock==3.19.1
      - fonttools==4.60.2
      - fsspec==2025.10.0
      - glfw==2.10.0
      - gym==0.26.2
      - gym-notices==0.1.0
      - gymnasium==0.29.1
      - gymnasium-notices==0.0.1
      - imageio==2.37.2
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - jax-jumpy==1.0.0
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - mujoco==2.3.1.post1
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - pandas==2.3.3
      - path==17.1.1
      - pillow==11.3.0
      - pyopengl==3.1.10
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scipy==1.13.1
      - six==1.17.0
      - stable-baselines3==2.7.1
      - torch==2.8.0
      - triton==3.4.0
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - zipp==3.23.0
prefix: /mnt/Dados/anaconda3/envs/trplab
